### ISSUE TITLE
add support for breaking the build if at least one pseudo-tested exists

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/pitest-descartes#142] opened 2020-10-21 07:29 UTC
We want to break the build if at least one pseudo-tested method exists.

Today, to break the build in CI based on Descartes, we need to write additional imperative code that analyzes the JSON file produced by Descartes.

It would be great to be able to simplify this, by configuring the `pom.xml` and break the build if at least one pseudo-tested method exists.

This would be similar what jacoco is doing to break the build based on coverage info, see https://www.jacoco.org/jacoco/trunk/doc/check-mojo.html

And its usage in Spoon: https://github.com/INRIA/spoon/pull/3641/files

**Comment by oscarlvp** [comment] 2020-10-21 07:34
Duplicate of #68

**Comment by oscarlvp** [comment] 2020-12-23 11:57
Closing duplicate

**Closed by oscarlvp** 2020-12-23 11:57 UTC
