### ISSUE TITLE
Wrong mutation coverage reported

### ISSUE THREAD

**Issue by mflorea** [STAMP-project/pitest-descartes#114] opened 2020-01-15 14:52 UTC
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [pitest-maven:1.4.10:mutationCoverage]
- **Execution Environment**: [Ubuntu 19.04]

#### Description

When I build [xwiki-commons-diff-xml](https://github.com/xwiki/xwiki-commons/tree/cff35addc98509a59937fe2e19757ded88915683/xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-xml) using:

    > mvn clean install -Pquality -Dxwiki.pitest.skip=false -Djacoco.skip=true

I get:

    Mutation score of 60 is below threshold of 96

The difference is quite significant. I checked the issues reported by Descartes and some of them seem to be wrong. For instance:

```
org.xwiki.diff.xml.internal.AbstractXMLDiffMarker
    applyPatch(org.w3c.dom.Element, org.xwiki.diff.Patch)
    This method is pseudo-tested.
    The body of this method can be removed and no test case fails.
    The following test cases execute the method:
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[14] src/test/resources/html/nestedDiffBlocks.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[11] src/test/resources/html/attributeDeletedInline.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[13] src/test/resources/html/childrenModifiedInline.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[20] src/test/resources/html/attributeInsertedBlock.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[10] src/test/resources/html/nodeIndexChange.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[4] src/test/resources/html/listItemInserted.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[3] src/test/resources/html/childrenDeletedInline.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[21] src/test/resources/html/childrenInsertedBlock.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[12] src/test/resources/html/attributeDeletedBlock.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[18] src/test/resources/html/childrenInsertedInline.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[17] src/test/resources/html/childrenModifiedBlock.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[1] src/test/resources/html/childrenDeletedBlock.test
        org.xwiki.diff.xml.internal.UnifiedHTMLDiffManagerTest.[8] src/test/resources/html/attributeInsertedInline.test
```

If I comment out the body of ``AbstractXMLDiffMarker#applyPatch(org.w3c.dom.Element, org.xwiki.diff.Patch)`` and run the tests I get lots of failures, including some from the test cases listed above (e.g. ``childrenDeletedInline.test``). So it looks like pitest/descartes is detecting the test cases correctly but not the fact that they fail.

[My test](https://github.com/xwiki/xwiki-commons/blob/cff35addc98509a59937fe2e19757ded88915683/xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-xml/src/test/java/org/xwiki/diff/xml/internal/UnifiedHTMLDiffManagerTest.java) is a bit special because it uses:

```
@ParameterizedTest
@MethodSource("getTestFiles")
```

But this hasn't created problems before. For instance, at this commit https://github.com/xwiki/xwiki-commons/tree/300ad03da64dad2749267a70d692e2dd14429351/xwiki-commons-core/xwiki-commons-diff/xwiki-commons-diff-xml the reported mutation coverage was OK (96). Basically the issue occurred at this commit https://github.com/xwiki/xwiki-commons/commit/d2101de970fecb3ef09b223a098d9ef96d8669e1#diff-7ddf5975d3bead4599efe91f451a4934 but I don't see what could have caused the significant drop in mutation coverage.

#### [Help on issue template](https://github.com/STAMP-project/pitest-descartes/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by vmassol** [comment] 2020-01-16 06:54
@oscarlvp hi, let me start by wishing you a happy new year 2020! Plenty of research success to you :)

Is there any chance you could help us diagnose this issue?

Thanks a lot
-Vincent

**Comment by oscarlvp** [comment] 2020-01-16 10:40
@vmassol best wishes for you too!
Yes, I have this issue in my priority list :)
As soon as I have an answer I'll let you know.

**Comment by oscarlvp** [comment] 2020-01-28 16:10
@mflorea is the build information available from your CI? I would like to inspect the report produced by PIT to see if the test is not being executed.

**Comment by oscarlvp** [comment] 2020-01-28 16:13
I checked here https://ci.xwiki.org/view/All/job/xwiki-commons_pitest/683/org.xwiki.commons$xwiki-commons-diff-xml/console, it seems that the build does not keep the report. I will check it locally.

**Comment by vmassol** [comment] 2020-01-30 15:56
Thanks @oscarlvp . Let me know if you need my help somewhere.

**Comment by oscarlvp** [comment] 2020-02-02 19:59
@mflorea @vmassol This issue seems to be solved in version 0.12 of **pitest-junit5-plugin**. 
I ran the analysis on xwiki-commons-diff-xml with version 0.12 and got a 98% mutation score and `applyPatch` was not pseudo-tested.
Please update the  **pitest-junit5-plugin** to the latest version and confirm if the issue is solved on your side.

**Comment by vmassol** [comment] 2020-02-02 20:56
Thanks @oscarlvp . Actually I've upgraded to 0.12 yesterday  but because I was testing if https://github.com/STAMP-project/pitest-descartes/issues/117 would be fixed by it (it's not unfortunately). I didn't think about testing this issue. I'll try to do that tomorrow. Thanks a lot for investigating it!

If you have some energy left, https://github.com/STAMP-project/pitest-descartes/issues/117 is an even bigger issue for us ATM. We suddenly have plenty of test modules (junit5 ones probably) suddenly failing pitest/descartes. Could be a regression  somewhere.

Thanks!

**Comment by oscarlvp** [comment] 2020-02-03 09:49
@vmassol  I'm unable to build this module in my computer. Some enforcer rules are failing. Is there an easy way to skip this verification?

**Comment by tmortagne** [comment] 2020-02-03 11:21
@oscarlvp the build errors you are reporting suggest you are building with a not very up to date version of xwiki-commons

Also I just reverted reflections version because of a regressions in it so better pulling again.

**Comment by oscarlvp** [comment] 2020-02-03 14:14
@tmortagne  Sorry, the comment before was meant to be in #117

**Comment by tmortagne** [comment] 2020-02-03 14:23
OK

**Comment by vmassol** [comment] 2020-02-03 14:31
I confirm that it works fine with version 0.12. Thanks @oscarlvp !

**Closed by vmassol** 2020-02-03 14:31 UTC
Labels: test-execution
